# Location vêtements

Vetement: {
  shape: sql_table
  vetement_id: int {constraint: primary_key}
  donneur_id: int {constraint: foreign_key}
  periode_id: int {constraint: foreign_key}
  type_vetement: String
  taux_usage: String
  date_reception: DateTime
}

Donneur: {
  shape: sql_table
  donneur_id: int {constraint: primary_key}
  nom: String
  prenom: String
  age: int
  sexe: String
  ville: String
}

Locataire: {
  shape: sql_table
  locataire_id: int {constraint: primary_key}
  periode_id: int {constraint: foreign_key}
  nom: String
  prenom: String
  age: int
  sexe: String
  ville: String
}

Période de location: {
  shape: sql_table
  periode_id: int {constraint: primary_key}
  date_debut_location: DateTime|null
  date_fin_location: DateTime|null
}

Vetement.donneur_id -- Donneur.donneur_id

Vetement.periode_id -- Période de location.periode_id
Locataire.periode_id -- Période de location.periode_id
